ALTER TABLE DYEXTN_COMBOBOX ADD column NO_OF_COLUMNS integer;
create table DYEXTN_ABSTRACT_FORM_CONTEXT (IDENTIFIER bigint not null auto_increment, FORM_LABEL varchar(255), CONTAINER_ID bigint, HIDE_FORM bit default 0, ACTIVITY_STATUS varchar(10), primary key (IDENTIFIER));
create table DYEXTN_ABSTRACT_RECORD_ENTRY (IDENTIFIER bigint not null auto_increment, MODIFIED_DATE date, MODIFIED_BY varchar(255), ACTIVITY_STATUS varchar(10), ABSTRACT_FORM_CONTEXT_ID bigint, primary key (IDENTIFIER));
alter table DYEXTN_ABSTRACT_RECORD_ENTRY add index FKA74A5FE4DDFB1974 (ABSTRACT_FORM_CONTEXT_ID), add constraint FKA74A5FE4DDFB1974 foreign key (ABSTRACT_FORM_CONTEXT_ID) references DYEXTN_ABSTRACT_FORM_CONTEXT (IDENTIFIER);
alter table DYEXTN_CATEGORY add USER_ID bigint;

