create table CATISSUE_AUDIT_EVENT (
   IDENTIFIER number(19,0) not null ,
   IP_ADDRESS varchar(20),
   EVENT_TIMESTAMP date,
   USER_ID number(19,0),
   COMMENTS varchar2(500),
   EVENT_TYPE varchar(20),
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_LOG (
   IDENTIFIER number(19,0) not null ,
   AUDIT_EVENT_ID number(19,0),
   primary key (IDENTIFIER)
);
create table CATISSUE_AUDIT_EVENT_DETAILS (
   IDENTIFIER number(19,0) not null ,
   ELEMENT_NAME varchar(150),
   AUDIT_EVENT_LOG_ID number(19,0),
   CURRENT_VALUE CLOB DEFAULT NULL,
   PREVIOUS_VALUE CLOB DEFAULT NULL,
   primary key (IDENTIFIER)
);
CREATE TABLE CATISSUE_DATA_AUDIT_EVENT_LOG
(
	IDENTIFIER NUMBER NOT NULL,
	OBJECT_IDENTIFIER NUMBER,
	OBJECT_NAME VARCHAR(50),
	PARENT_LOG_ID NUMBER,
	PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE CATISSUE_LOGIN_AUDIT_EVENT_LOG
(
	IDENTIFIER NUMBER NOT NULL,
	LOGIN_TIMESTAMP DATE,
	USER_LOGIN_ID VARCHAR(20),
	LOGIN_SOURCE_ID NUMBER,
	LOGIN_IP_ADDRESS VARCHAR(20),
	IS_LOGIN_SUCCESSFUL VARCHAR(10),
	PRIMARY KEY (IDENTIFIER)
) ;

ALTER TABLE CATISSUE_DATA_AUDIT_EVENT_LOG ADD CONSTRAINT FK5C07745DC62F96A411
FOREIGN KEY (IDENTIFIER) REFERENCES CATISSUE_AUDIT_EVENT_LOG (IDENTIFIER);

ALTER TABLE CATISSUE_DATA_AUDIT_EVENT_LOG ADD CONSTRAINT FK5C07745DC62F96A412 
FOREIGN KEY (PARENT_LOG_ID) REFERENCES CATISSUE_DATA_AUDIT_EVENT_LOG (IDENTIFIER);
